version: "3.8"
services:
  backend:
    image: "palmillas/spring-react-fullstack:2.5.2022.20.49.12"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev